name: CI
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        version:
          - '1.10'
          - '1.11'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x86
          - x64
        include:
          - os: ubuntu-latest
            prefix: xvfb-run
        exclude:
          # Remove some configurations from the build matrix to reduce CI time.
          # See https://github.com/marketplace/actions/setup-julia-environment
          # MacOS not available on x86
          - {os: 'macOS-latest', arch: 'x86'}
          # Don't test on all versions
          - {os: 'macOS-latest', version: 'nightly'}
          - {os: 'windows-latest', version: 'nightly'}
          - {os: 'windows-latest', arch: 'x86'}
          - {arch: 'x86', version: 'nightly'}
    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
        with:
          coverage: false
          prefix: ${{ matrix.prefix }}
